-- 1 Question: List all information for all network zones.
SELECT 
* 
FROM Zone;

-- 2 Question: Retrieve all details for devices that are currently active.
SELECT 
* 
FROM Device 
WHERE Status = 'Active';

-- 3 Question: Get a list of all employees working in the IT department.
SELECT 
* 
FROM Employee 
WHERE Department = 'IT';

-- 4 Question: Retrieve the first 100 entries from the network log.
SELECT 
* 
FROM NetworkLog 
LIMIT 100;

-- 5 Question: List all unique types of devices present in the system.
SELECT DISTINCT DeviceType FROM Device;

-- 6 Question: What is the total number of employees?
SELECT COUNT(*) FROM Employee;

-- 7 Question: What is the total number of entries in the network log?
SELECT COUNT(*) FROM NetworkLog;

-- 8 Question: List all security incidents with a 'High' severity level.
SELECT * FROM Incident WHERE Severity = 'High';

-- 9 Question: Get today's bandwidth usage records
SELECT * FROM BandwidthUsage WHERE Date = CURRDATE();

-- 10 Find the names of zones located at the Headquarters (HQ).
SELECT ZoneName FROM Zone WHERE Location LIKE '%HQ%';

-- 11 Question: Identify all devices installed after January 1st, 2023.
SELECT * FROM Device WHERE InstallDate > '2023-01-01';

-- 12 Question: Retrieve all network logs with a 'Failed' status.
SELECT * FROM NetworkLog WHERE Status = 'Failed';

-- 13 Question: List all network logs that occurred via VPN.
SELECT * FROM NetworkLog WHERE AccessType = 'VPN';

-- 14 Question: Retrieve information for all employees whose role is 'Manager'
SELECT * FROM Employee WHERE Role = 'Manager';

-- 15 Question: List all incidents classified as 'Downtime'
SELECT * FROM Incident WHERE IncidentType = 'Downtime';

-- 16 Question: Show bandwidth usage records ordered by highest usage first.
SELECT * FROM BandwidthUsage ORDER BY TotalUsageGB DESC;

-- 17 Question: List devices ordered by their installation date, from newest to oldest
SELECT * FROM Device ORDER BY InstallDate DESC;

-- 18 Question: Find all network logs where data usage exceeded 1000 MB
SELECT * FROM NetworkLog WHERE DataUsageMB > 1000;

-- 19 Question: Identify network logs with high latency (greater than 200ms)
SELECT * FROM NetworkLog WHERE LatencyMS > 200;

-- 20 Question: Find all employees whose names start with the letter 'A'. 
SELECT * FROM Employee WHERE Name LIKE 'A%';

-- 21 Retrieve all devices along with their corresponding zone names.
SELECT d.DeviceID, z.ZoneName
FROM Device d
JOIN Zone z ON d.ZoneID = z.ZoneID;

-- 22 List all network logs with the employee name who generated them.
SELECT n.LogID, e.Name
FROM NetworkLog n
JOIN Employee e ON n.EmployeeID = e.EmployeeID;

-- 23 Show each network log along with the device type used.
SELECT n.LogID, d.DeviceType
FROM NetworkLog n
JOIN Device d ON n.DeviceID = d.DeviceID;

-- 24 Get employee name, device, and zone for each network activity.
SELECT e.Name, z.ZoneName
FROM NetworkLog n
JOIN Employee e ON n.EmployeeID = e.EmployeeID
JOIN Device d ON n.DeviceID = d.DeviceID
JOIN Zone z ON d.ZoneID = z.ZoneID;

-- 25 Count how many logs are generated by each device (include devices with zero logs).
SELECT d.DeviceID, COUNT(n.LogID)
FROM Device d
LEFT JOIN NetworkLog n ON d.DeviceID = n.DeviceID
GROUP BY d.DeviceID;

-- 26 Calculate total bandwidth usage per zone.
SELECT z.ZoneName, SUM(b.TotalUsageGB)
FROM BandwidthUsage b
JOIN Zone z ON b.ZoneID = z.ZoneID
GROUP BY z.ZoneName;

-- 27 Count number of employees in each department.
SELECT e.Department, COUNT(*)
FROM Employee e
GROUP BY e.Department;

-- 28 Count number of devices by device type.
SELECT d.DeviceType, COUNT(*)
FROM Device d
GROUP BY d.DeviceType;

-- 29 Find total number of devices in each zone.
SELECT z.ZoneName, COUNT(d.DeviceID)
FROM Zone z
JOIN Device d ON z.ZoneID = d.ZoneID
GROUP BY z.ZoneName;

-- 30 Get total data usage per employee.
SELECT e.Name, SUM(n.DataUsageMB)
FROM NetworkLog n
JOIN Employee e ON n.EmployeeID = e.EmployeeID
GROUP BY e.Name;

-- 31 Find average latency for each zone.
SELECT z.ZoneName, AVG(n.LatencyMS)
FROM NetworkLog n
JOIN Device d ON n.DeviceID = d.DeviceID
JOIN Zone z ON d.ZoneID = z.ZoneID
GROUP BY z.ZoneName;

-- 32 Get maximum data usage recorded for each device.
SELECT d.DeviceID, MAX(n.DataUsageMB)
FROM NetworkLog n
JOIN Device d ON n.DeviceID = d.DeviceID
GROUP BY d.DeviceID;

-- 33 Count number of logs per employee (include employees with no activity).
SELECT e.Name, COUNT(n.LogID)
FROM Employee e
LEFT JOIN NetworkLog n ON e.EmployeeID = n.EmployeeID
GROUP BY e.Name;

-- 34 Count total incidents per zone.
SELECT z.ZoneName, COUNT(i.IncidentID)
FROM Incident i
JOIN Device d ON i.DeviceID = d.DeviceID
JOIN Zone z ON d.ZoneID = z.ZoneID
GROUP BY z.ZoneName;

-- 35 Find average latency per device type (Router, Switch, Server).
SELECT d.DeviceType, AVG(n.LatencyMS)
FROM NetworkLog n
JOIN Device d ON n.DeviceID = d.DeviceID
GROUP BY d.DeviceType;

-- 36 Calculate total data usage by each department.
SELECT e.Department, SUM(n.DataUsageMB)
FROM NetworkLog n
JOIN Employee e ON n.EmployeeID = e.EmployeeID
GROUP BY e.Department;

-- 37 Find peak bandwidth usage per zone.
SELECT z.ZoneName, MAX(b.PeakUsageGB)
FROM BandwidthUsage b
JOIN Zone z ON b.ZoneID = z.ZoneID
GROUP BY z.ZoneName;

-- 38 Count number of incidents per device.
SELECT d.DeviceID, COUNT(i.IncidentID)
FROM Device d
LEFT JOIN Incident i ON d.DeviceID = i.DeviceID
GROUP BY d.DeviceID;

-- 39 Find average latency per employee.
SELECT e.Name, AVG(n.LatencyMS)
FROM NetworkLog n
JOIN Employee e ON n.EmployeeID = e.EmployeeID
GROUP BY e.Name;

-- 40  Count how many unique employees accessed each zone.
SELECT z.ZoneName, COUNT(DISTINCT e.EmployeeID)
FROM NetworkLog n
JOIN Employee e ON n.EmployeeID = e.EmployeeID
JOIN Device d ON n.DeviceID = d.DeviceID
JOIN Zone z ON d.ZoneID = z.ZoneID
GROUP BY z.ZoneName;

-- 41. Identify the top 5 employees with the highest total data usage.
SELECT EmployeeID, SUM(DataUsageMB) AS usagee
FROM NetworkLog
GROUP BY EmployeeID
ORDER BY usagee DESC
LIMIT 5;

-- 42. Find devices whose average latency is greater than 150 ms.
SELECT DeviceID, AVG(LatencyMS)
FROM NetworkLog
GROUP BY DeviceID
HAVING AVG(LatencyMS) > 150;

-- 43. Calculate total data usage per zone.
SELECT ZoneID, SUM(DataUsageMB)
FROM NetworkLog
GROUP BY ZoneID;

-- Count total number of successful network requests.
SELECT COUNT(*) FROM NetworkLog WHERE Status = 'Success';

-- 45 Count total number of failed network requests.
SELECT COUNT(*) FROM NetworkLog WHERE Status = 'Failed';

-- 46. Find devices with the highest number of failed logs.
SELECT DeviceID, COUNT(*) AS FailCount
FROM NetworkLog
WHERE Status = 'Failed'
GROUP BY DeviceID;

-- 47. Count total number of login attempts per employee.
SELECT EmployeeID, COUNT(*) AS LoginAttempts
FROM NetworkLog
GROUP BY EmployeeID;

-- 48. Calculate daily data usage trend.
SELECT DATE(Timestamp), SUM(DataUsageMB)
FROM NetworkLog
GROUP BY DATE(Timestamp);

-- 49. Find number of network activities per hour of the day.
SELECT HOUR(Timestamp), COUNT(*)
FROM NetworkLog
GROUP BY HOUR(Timestamp);

-- 50. Calculate total data usage per device.
SELECT DeviceID, SUM(DataUsageMB)
FROM NetworkLog
GROUP BY DeviceID;

-- 51. Find the maximum data usage per employee in a single session.
SELECT EmployeeID, MAX(DataUsageMB)
FROM NetworkLog
GROUP BY EmployeeID;

-- 52. Find the minimum latency recorded.
SELECT MIN(LatencyMS) FROM NetworkLog;

-- 53. Find the maximum latency recorded.
SELECT MAX(LatencyMS) FROM NetworkLog;

-- 54. Calculate the average latency across all logs.
SELECT AVG(LatencyMS) FROM NetworkLog;

-- 55. Calculate average peak bandwidth usage per zone.
SELECT ZoneID, AVG(PeakUsageGB)
FROM BandwidthUsage
GROUP BY ZoneID;

-- 56. Calculate total peak bandwidth usage per zone.
SELECT ZoneID, SUM(PeakUsageGB)
FROM BandwidthUsage
GROUP BY ZoneID;

-- 57. Count number of unique employees accessing the network.
SELECT COUNT(DISTINCT EmployeeID) FROM NetworkLog;

-- 58. Count number of unique devices used in logs.
SELECT COUNT(DISTINCT DeviceID) FROM NetworkLog;

-- 59. Count total number of logs per device.
SELECT DeviceID, COUNT(*) AS TotalLogs
FROM NetworkLog
GROUP BY DeviceID;

-- 60. Identify employees whose total data usage exceeds 5000 MB.
SELECT EmployeeID, SUM(DataUsageMB)
FROM NetworkLog
GROUP BY EmployeeID
HAVING SUM(DataUsageMB) > 5000;

-- 61. Calculate the total data usage per employee using a window function (without GROUP BY).
SELECT EmployeeID,
SUM(DataUsageMB) OVER (PARTITION BY EmployeeID) AS TotalUsage
FROM NetworkLog;

-- 62. Find the average latency per device using window functions.
SELECT DeviceID,
AVG(LatencyMS) OVER (PARTITION BY DeviceID)
FROM NetworkLog;

-- 63. Assign a row number to each network log based on highest data usage.
SELECT *,
ROW_NUMBER() OVER (ORDER BY DataUsageMB DESC) AS rank_no
FROM NetworkLog;

-- 64. Rank network logs based on data usage (allow gaps in ranking).
SELECT *,
RANK() OVER (ORDER BY DataUsageMB DESC) AS rnk
FROM NetworkLog;

-- 65. Assign a dense rank to logs based on data usage (no gaps).
SELECT *,
DENSE_RANK() OVER (ORDER BY DataUsageMB DESC)
FROM NetworkLog;

-- 66. Compare current data usage with the previous usage for each employee.
SELECT *,
LAG(DataUsageMB) OVER (PARTITION BY EmployeeID ORDER BY Timestamp)
FROM NetworkLog;

-- 67. Show the next data usage value for each employee session.
SELECT *,
LEAD(DataUsageMB) OVER (PARTITION BY EmployeeID ORDER BY Timestamp)
FROM NetworkLog;

-- 68. Get the first data usage value per employee (earliest record).
SELECT *,
FIRST_VALUE(DataUsageMB) OVER (PARTITION BY EmployeeID ORDER BY Timestamp)
FROM NetworkLog;

-- 69. Get the last data usage value per employee (latest record).
SELECT *,
LAST_VALUE(DataUsageMB) OVER (PARTITION BY EmployeeID ORDER BY Timestamp)
FROM NetworkLog;

-- 70. Calculate cumulative data usage over time across all logs.
SELECT EmployeeID,
SUM(DataUsageMB) OVER (ORDER BY Timestamp)
FROM NetworkLog;

-- 71. Divide logs into 4 equal buckets (quartiles) based on data usage.
SELECT *,
NTILE(4) OVER (ORDER BY DataUsageMB DESC)
FROM NetworkLog;

-- 72. Calculate the percent rank of each log based on data usage.
SELECT *,
PERCENT_RANK() OVER (ORDER BY DataUsageMB)
FROM NetworkLog;

-- 73. Find the cumulative distribution of data usage values.
SELECT *,
CUME_DIST() OVER (ORDER BY DataUsageMB)
FROM NetworkLog;

-- 74. Calculate running total of data usage per device over time.
SELECT *,
SUM(DataUsageMB) OVER (PARTITION BY DeviceID ORDER BY Timestamp)
FROM NetworkLog;

-- 75. Find average latency per employee using window function.
SELECT *,
AVG(LatencyMS) OVER (PARTITION BY EmployeeID)
FROM NetworkLog;

-- 76. Count total logs per device using window function.
SELECT *,
COUNT(*) OVER (PARTITION BY DeviceID)
FROM NetworkLog;

-- 77. Find the maximum data usage per employee using window function.
SELECT *,
MAX(DataUsageMB) OVER (PARTITION BY EmployeeID)
FROM NetworkLog;

-- 78. Find the minimum data usage per employee using window function.
SELECT *,
MIN(DataUsageMB) OVER (PARTITION BY EmployeeID)
FROM NetworkLog;

-- 79. Calculate total data usage per zone using window function (without GROUP BY).
SELECT *,
SUM(DataUsageMB) OVER (PARTITION BY ZoneID)
FROM NetworkLog;

-- 80. Assign row numbers to logs partitioned by device and ordered by latest timestamp.
SELECT *,
ROW_NUMBER() OVER (PARTITION BY DeviceID ORDER BY Timestamp DESC)
FROM NetworkLog;

-- 81 Multiple failed logins
SELECT EmployeeID, COUNT(*)
FROM NetworkLog
WHERE Status = 'Failed'
GROUP BY EmployeeID
HAVING COUNT(*) > 5;

-- 82 High data transfer anomaly
SELECT *
FROM NetworkLog
WHERE DataUsageMB > (
    SELECT AVG(DataUsageMB) * 3 FROM NetworkLog
);

-- 83 Unusual access time (night)
SELECT *
FROM NetworkLog
WHERE HOUR(Timestamp) BETWEEN 0 AND 5;

-- 84 Device with too many incidents
SELECT DeviceID, COUNT(*)
FROM Incident
GROUP BY DeviceID
HAVING COUNT(*) > 10;

-- 85 Sudden spike detection
SELECT *,
LAG(DataUsageMB) OVER (ORDER BY Timestamp) AS prev       -- Window function
FROM NetworkLog;

-- 86 External + high usage
SELECT *
FROM NetworkLog
WHERE AccessType = 'External'
AND DataUsageMB > 500;

-- 87 Repeated failed attempts same device
SELECT DeviceID, COUNT(*)
FROM NetworkLog
WHERE Status = 'Failed'
GROUP BY DeviceID
HAVING COUNT(*) > 10;

-- 88 High latency + success
SELECT *
FROM NetworkLog
WHERE LatencyMS > 300 AND Status = 'Success';

-- 89 Employees accessing multiple zones
SELECT EmployeeID, COUNT(DISTINCT ZoneID)
FROM NetworkLog
GROUP BY EmployeeID;

-- 90 Device inactive but logs present
SELECT d.DeviceID
FROM Device d
JOIN NetworkLog n ON d.DeviceID = n.DeviceID
WHERE d.Status = 'Inactive';

-- 91 Same user multiple devices short time
SELECT EmployeeID, COUNT(DISTINCT DeviceID)
FROM NetworkLog
GROUP BY EmployeeID
HAVING COUNT(DISTINCT DeviceID) > 3;

-- 92 Continuous failures
SELECT *
FROM NetworkLog
WHERE Status = 'Failed';

-- 93 High peak bandwidth anomaly
SELECT *
FROM BandwidthUsage
WHERE PeakUsageGB > (                           
    SELECT AVG(PeakUsageGB) * 2 FROM BandwidthUsage
);

-- 94 Incident duration
SELECT IncidentID,
TIMESTAMPDIFF(MINUTE, StartTime, EndTime)
FROM Incident;

-- 95 Long downtime
SELECT *
FROM Incident
WHERE TIMESTAMPDIFF(HOUR, StartTime, EndTime) > 5;

-- 96 Zone with max incidents
SELECT ZoneID, COUNT(*)
FROM Incident i
JOIN Device d ON i.DeviceID = d.DeviceID
GROUP BY ZoneID
ORDER BY COUNT(*) DESC
LIMIT 1;

-- 97 Employee abnormal latency
SELECT EmployeeID, AVG(LatencyMS)
FROM NetworkLog
GROUP BY EmployeeID
HAVING AVG(LatencyMS) > 200;

-- 98 Frequent VPN users
SELECT EmployeeID, COUNT(*)
FROM NetworkLog
WHERE AccessType = 'VPN'
GROUP BY EmployeeID
ORDER BY COUNT(*) DESC;

-- 99 Peak hour detection
SELECT HOUR(Timestamp), COUNT(*)
FROM NetworkLog
GROUP BY HOUR(Timestamp)
ORDER BY COUNT(*) DESC;

-- 100 Data usage percentile (top users)
SELECT *
FROM (                                              -- sub query in from
    SELECT EmployeeID,
           SUM(DataUsageMB) AS total_usage,
           NTILE(10) OVER (ORDER BY SUM(DataUsageMB) DESC) AS bucket
    FROM NetworkLog
    GROUP BY EmployeeID
) t
WHERE bucket = 1;  -- 1 for true

